name: Build RPM and add them to a release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-rpms:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create tarball
        shell: bash
        run: |
          version="$(grep Version jobinfo.spec | awk '{print $2}')"
          mkdir SOURCES
          mkdir SPECS
          cp hb-jobinfo.spec SPECS
          mkdir hb-jobinfo-${version}
          cp hb-jobinfo jobinfo-${version}
          tar -czf SOURCES/hb-jobinfo-${version}.tar.gz hb-jobinfo-${version}

      - name: rpmbuild rockylinux8
        uses: ./.github/actions/rpmbuild-rockylinux8/

      - name: upload rpm package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: RPM package
          path: ${{ github.workspace }}/noarch/hb-jobinfo*.rpm

  create-release:
    needs: [build-rpms]
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: find release version in tag
        id: find_version
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: download RPM packages
        uses: actions/download-artifact@v2
        with:
          name: RPM package
          path: ./build_artifacts

      - name: find filenames of downloaded packages
        id: find_filenames
        shell: bash
        run: |
          ls -1 -R .
          echo ::set-output name=package_filenames::$(find ./build_artifacts -name hb-jobinfo*.rpm)

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.find_version.outputs.version }}
          name: slurm-jobinfo ${{ steps.find_version.outputs.version }}
          body: >
            slurm-jobinfo release ${{ steps.find_version.outputs.version }}
          files: ${{ steps.find_filenames.outputs.package_filenames }}
          gzip: false
